#!/bin/sh
set -Eeuo pipefail

: ${DOTFILES_PATH:="$HOME/dotfiles"}

ARGS=('')
for a in "$@"; do
  ARGS=(${ARGS[@]} "$a")
done

info() {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user() {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail() {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit 1
}

check_os() {
  info 'Checking operating system...'

  if [ "$(uname -s)" != "Darwin" ]
  then
    fail 'These dotfiles require MacOS'
  else
    success 'Operating system ok'
  fi
}

install_homebrew () {
  command -v 'brew' > /dev/null 2>&1 && return

  $DOTFILES_PATH/homebrew/install.sh 2>&1
}

install_ansible () {
  command -v 'ansible' > /dev/null 2>&1 && return

  info 'Installing ansible...'
  brew install ansible
  success 'Finished installing ansible'
}

provision () {
  info 'Provisioning machine...'
  $DOTFILES_PATH/provisioning/run.sh ${ARGS[@]}
  success 'Finished provisioning machine'
}

main() {
  check_os
  install_homebrew
  install_ansible
  provision
}

main
