- name: check if firacode is installed
  stat:
    path: /Library/Fonts/FiraCode-Regular.otf
  register: firacode

- name: download firecode
  git:
    repo: git@github.com:tonsky/FiraCode.git
    dest: /tmp/firacode
    depth: 1
  when: firacode.stat.exists == false

- name: install firacode
  command: cp -a /tmp/firacode/distr/otf/. /Library/Fonts/
  become: yes
  when: firacode.stat.exists == false

- name: delete temporary files
  file:
    state: absent
    path: /tmp/firacode
