#  Base
#-----------------------------------------------
[[plugins]] # dark powered vim/neovim plugin manager
repo = 'Shougo/dein.vim'


#  Editing
#-----------------------------------------------
[[plugins]] # Vim plugin for intensely orgasmic commenting
repo = 'scrooloose/nerdcommenter'

#  Completion
#-----------------------------------------------

#  Utils
#-----------------------------------------------


#  Appearance
#-----------------------------------------------
[[plugins]] # candle theme
repo = 'creasty/candle.vim'