#  Base
#-----------------------------------------------
[[plugins]] # a Vim plugin which shows a git diff in the gutter (sign column) and stages/undoes hunks.
repo  = 'airblade/vim-gitgutter'
on_if = 1

#  Editing
#-----------------------------------------------


#  Programming languages
#-----------------------------------------------
[[plugins]] # go development plugin for Vim
repo  = 'fatih/vim-go'
on_ft = ['go']

[[plugins]] # basic vim/terraform integration
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']

[[plugins]] # syntax highlighting for Swift
repo = 'keith/swift.vim'
on_ft = 'swift'

[[plugins]] # Vastly improved Javascript indentation and syntax support
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]] # React JSX syntax pretty highlighting for vim
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript', 'javascriptreact', 'typescriptreact']

[[plugins]] # TypesSript syntax files for Vim
repo  = 'herringtondarkholme/yats.vim'
on_ft = ['typescript', 'typescriptreact']

[[plugins]] # Vim syntax highlighting for Google's Protocol Buffers
repo  = 'uarun/vim-protobuf'
on_ft = ['proto']

[[plugins]] # Kotlin plugin for Vim. Featuring: syntax highlighting, basic indentation, Syntastic support
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

#  Completion
#-----------------------------------------------
[[plugins]] # emmet for vim: HTML and CSS hi-speed coding
repo    = 'mattn/emmet-vim'
on_func = ['emmet']

#  Linting
#-----------------------------------------------
[[plugins]] # asynchronous linting/fixing for Vim and Language Server Protocol (LSP) integration
repo = 'w0rp/ale'
on_ft = ['sh']

#  Navigation
#-----------------------------------------------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]] # fzf ❤️ vim, A command-line fuzzy finder
repo  = 'junegunn/fzf.vim'
depends = ['fzf']
on_if = 1

#  Social
#-----------------------------------------------
[[plugins]]
repo = 'wakatime/vim-wakatime'
