#  Editing
#-----------------------------------------------


#  Completion
#-----------------------------------------------
[[plugins]] # syntax source for neocomplete/deoplete/ncm
repo    = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']
on_i    = 1
hook_source = '''
let g:necosyntax#min_keyword_length = 3
'''

[[plugins]] # vim source for neocomplete/deoplete
repo    = 'Shougo/neco-vim'
depends = ['deoplete.nvim']
on_ft   = ['vim']

[[plugins]] # asynchronous Go completion for Neovim. deoplete source for Go
repo    = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
build   = 'make'
on_ft   = ['go']
hook_source = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]] # emmet for vim: HTML and CSS hi-speed coding
repo    = 'mattn/emmet-vim'
on_func = ['emmet']

#  Navigation
#-----------------------------------------------
[[plugins]] # fzf ❤️ vim, A command-line fuzzy finder
repo  = 'junegunn/fzf.vim'
on_if = 1
