#  Base
#-----------------------------------------------
[[plugins]] # dark powered vim/neovim plugin manager
repo = 'Shougo/dein.vim'


#  Editing
#-----------------------------------------------
[[plugins]] # vim plugin for intensely orgasmic commenting
repo = 'scrooloose/nerdcommenter'

[[plugins]] # deleting, changing, and adding surroundings
repo = 'vim-scripts/surround.vim'

[[plugins]] # vim motions on speed!
repo = 'easymotion/vim-easymotion'

#  Auto-completion
#-----------------------------------------------
[[plugins]] # yet another remote plugin framework for neovim
repo = 'roxma/nvim-yarp'
if   = "!has('nvim')"

[[plugins]] # a compatibility layer for neovim rpc client working on vim8
repo = 'roxma/vim-hug-neovim-rpc'
if   = "!has('nvim')"

[[plugins]] # dark powered asynchronous completion framework for neovim/vim8
repo    = 'Shougo/deoplete.nvim'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']


#  Utils
#-----------------------------------------------
[[plugins]] # a git wrapper so awesome, it should be illegal
repo = 'tpope/vim-fugitive'


#  Appearance
#-----------------------------------------------
[[plugins]] # candle theme
repo = 'creasty/candle.vim'
