#  Base
#-----------------------------------------------
[[plugins]] # dark powered vim/neovim plugin manager
repo = 'Shougo/dein.vim'


#  Editing
#-----------------------------------------------
[[plugins]] # vim plugin for intensely orgasmic commenting
repo = 'scrooloose/nerdcommenter'

[[plugins]] # deleting, changing, and adding surroundings
repo = 'vim-scripts/surround.vim'

[[plugins]] # vim motions on speed!
repo = 'easymotion/vim-easymotion'

#  Auto-completion
#-----------------------------------------------
[[plugins]] # Intellisense engine for Vim8 & Neovim, full language server protocol support as VSCode
repo   = 'neoclide/coc.nvim'
rev    = 'release'
merged = 0


#  Utils
#-----------------------------------------------
[[plugins]] # a git wrapper so awesome, it should be illegal
repo = 'tpope/vim-fugitive'


#  Appearance
#-----------------------------------------------
[[plugins]] # candle theme
repo = 'creasty/candle.vim'
