#  Base
#-----------------------------------------------
[[plugins]] # a Vim plugin which shows a git diff in the gutter (sign column) and stages/undoes hunks.
repo  = 'airblade/vim-gitgutter'
on_if = 1

#  Editing
#-----------------------------------------------


#  Programming languages
#-----------------------------------------------
[[plugins]] # go development plugin for Vim
repo  = 'fatih/vim-go'
on_ft = ['go']

[[plugins]] # basic vim/terraform integration
repo = 'hashivim/vim-terraform'
on_ft = ['hcl']


#  Completion
#-----------------------------------------------
[[plugins]] # syntax source for neocomplete/deoplete/ncm
repo    = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']
on_if    = 1
hook_source = '''
let g:necosyntax#min_keyword_length = 3
'''

[[plugins]] # vim source for neocomplete/deoplete
repo    = 'Shougo/neco-vim'
depends = ['deoplete.nvim']
on_ft   = ['vim']

[[plugins]] # asynchronous Go completion for Neovim. deoplete source for Go
repo    = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
build   = 'make'
on_ft   = ['go']
hook_source = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]] # emmet for vim: HTML and CSS hi-speed coding
repo    = 'mattn/emmet-vim'
on_func = ['emmet']

#  Linting
#-----------------------------------------------
[[plugins]] # asynchronous linting/fixing for Vim and Language Server Protocol (LSP) integration
repo = 'w0rp/ale'
on_ft = ['sh']

#  Navigation
#-----------------------------------------------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]] # fzf ❤️ vim, A command-line fuzzy finder
repo  = 'junegunn/fzf.vim'
depends = ['fzf']
on_if = 1
