- set_fact:
    homebrew: {}

- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: add taps
  homebrew_tap:
    name: '{{ homebrew.taps }}'
    state: present

- name: install cask applications
  homebrew_cask:
    name:  '{{ homebrew.applications }}'
    state: present
  when: homebrew.applications

- name: install homebrew packages
  homebrew:
    name:  '{{ homebrew.packages }}'
    state: present
  when: homebrew.packages
