- set_fact:
    java: {}

- name: install openjdk
  homebrew:
    name: openjdk
    state: present

- name: tap adoptopenjdk/openjdk
  homebrew_tap:
    tap:   adoptopenjdk/openjdk
    state: present

- name: install old versions
  homebrew_cask:
    name: adoptopenjdk8
    state: present

- name: install jenv
  homebrew:
    name: jenv
    state: present

- name: enable export plugin
  command: |
    bash -lc 'jenv enable-plugin export'

- name: enable export plugin
  command: |
    bash -lc 'jenv add "$(/usr/libexec/java_home)"'
