homebrew:
  applications:
    - 1password
    - alfred
    - discord
    - firefox
    - gitify
    - google-chrome
    - insomnia
    - karabiner-elements
    - keybase
    - postgres
    - quicklook-json
    - slack
    - spotify
    - transmission
    - visual-studio-code

  packages:
    - ack
    - coreutils
    - direnv
    - fzf
    - go
    - imagemagick
    - jq
    - node
    - pgweb
    - rbenv
    - readline
    - ripgrep
    - screen
    - tmux
    - tree
    - wget
    - yarn

link:
  bash/bash_profile:         .bash_profile
  bash/bashrc:               .bashrc
  git/gitconfig:             .gitconfig
  git/gitignore:             .gitignore
  mac/aliases:               .aliases
  mac/exports:               .exports
  mac/hushlogin:             .hushlogin
  mac/inputrc:               .inputrc
  ruby/irbrc:                .irbrc
  ruby/pryrc:                .pryrc
  screen/screenrc:           .screenrc
  tmux/tmux.conf:            .tmux.conf
  vim/gvimrc:                .gvimrc
  vim/vimrc:                 .vimrc
  vim:                       .vim
  wget:                      .wgetrc
  karabiner:                 .config/karabiner
