homebrew:
  taps:
    - homebrew/cask-fonts
  applications:
    - 1password
    - alfred
    - anki
    - background-music
    - contexts
    - discord
    - docker
    - enjoyable
    - firefox
    - gitify
    - gitup
    - google-chrome
    - google-cloud-sdk
    - imageoptim
    - insomnia
    - iterm2
    - karabiner-elements
    - keybase
    - moom
    - ngrok
    - postgres
    - quicklook-json
    - sketch
    - slack
    - spotify
    - transmission
    - visual-studio-code
    - font-fira-code

  packages:
    - ack
    - carthage
    - coreutils
    - direnv
    - docker
    - envchain
    - fzf
    - github/gh/gh
    - go
    - grc
    - imagemagick
    - jq
    - mitmproxy
    - node
    - pgweb
    - rbenv
    - readline
    - ripgrep
    - screen
    - shellcheck
    - terraform
    - tmux
    - tree
    - watchman
    - wget

link:
  zsh/zshrc:                 .zshrc
  zsh/zshrc.d:               zshrc.d
  git/gitconfig:             .gitconfig
  git/gitignore:             .gitignore
  git/hooks:                 gitconfig/hooks
  grc:                       .grc
  karabiner:                 .config/karabiner
  mac/aliases:               .aliases
  mac/exports:               .exports
  mac/hushlogin:             .hushlogin
  mac/inputrc:               .inputrc
  ruby/irbrc:                .irbrc
  ruby/pryrc:                .pryrc
  screen/screenrc:           .screenrc
  tmux/tmux.conf:            .tmux.conf
  vim/gvimrc:                .gvimrc
  vim/vimrc:                 .vimrc
  vim:                       .vim
  vim:                       .config/nvim
  wget:                      .wgetrc

anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'
  libexec_dir: '{{ home_path }}/.anyenv/libexec'

golang:
  packages:
    # dev tools
    - golang.org/x/lint/golint           # Golint is a linter for Go source code
    - github.com/nsf/gocode              # An autocompletion daemon for the Go programming language
    - github.com/rogpeppe/godef          # find symbol information in Go source
    - github.com/izumin5210/gex/cmd/gex  # Dev tool dependency manager

nodejs:
  default_packages_path: '{{ dotfiles_path }}/config/nodenv/default-packages'
  versions:
    - '12.18.3'
  plugins:
    - nodenv/nodenv-default-packages
