homebrew:
  taps:
    - jakehilborn/jakehilborn
  applications:
    # - 1password
    - alfred
    # - anki
    # Disabled until antonve/tools/screen-manager removes the deprecated appcast stanza.
    # - antonve/tools/screen-manager
    # - background-music
    - contexts
    # - discord
    # - docker
    # - enjoyable
    - firefox
    - gitify
    # - google-chrome
    - google-cloud-sdk
    - imageoptim
    - insomnia
    - iterm2
    - karabiner-elements
    # - moom
    - postgres-unofficial
    # - quicklook-json
    # - slack
    - spotify
    - visual-studio-code
    - font-fira-code

  packages:
    - ack
    - bat
    - bazel
    - carthage
    - coreutils
    - direnv
    - displayplacer
    - dive
    - docker
    - envchain
    - fzf
    - homebrew/core/gh
    - git-delta
    - go
    - grc
    - grpcurl
    - helm
    - imagemagick
    - jq
    - kubernetes-cli
    - mitmproxy
    - pgweb
    - pure
    - rbenv
    - readline
    - ripgrep
    - screen
    - shellcheck
    - skopeo
    - tfenv
    - tilt
    - tmux
    - tree
    - watchman
    - wget
    - yq

link:
  shell/profile:             .profile
  bash/profile:              .bash_profile
  zsh/zshrc:                 .zshrc
  zsh/zshrc.d:               zshrc.d
  git/gitconfig:             .gitconfig
  git/gitignore:             .gitignore
  ghostty:                   .config/ghostty
  ghostty/config.ghostty:    "Library/Application Support/com.mitchellh.ghostty/config.ghostty"
  grc:                       .grc
  karabiner:                 .config/karabiner
  mac/hushlogin:             .hushlogin
  mac/inputrc:               .inputrc
  ruby/irbrc:                .irbrc
  ruby/pryrc:                .pryrc
  screen/screenrc:           .screenrc
  herdr/config.toml:         .config/herdr/config.toml
  tmux/tmux.conf:            .tmux.conf
  vim/gvimrc:                .gvimrc
  vim:                       .config/nvim
  wget:                      .wgetrc

nodejs:
  nvm_dir: '{{ home_path }}/.nvm'
  install_version: '--lts'
  default_alias: 'lts/*'
