homebrew:
  taps:
    - homebrew/cask-fonts
    - hotchemi/tap
    - jakehilborn/jakehilborn
    - instrumenta/instrumenta
  applications:
    - 1password
    - alfred
    - anki
    - antonve/tools/screen-manager
    - background-music
    - contexts
    - discord
    - docker
    - enjoyable
    - firefox
    - gitify
    - gitup
    - google-chrome
    - google-cloud-sdk
    - imageoptim
    - insomnia
    - iterm2
    - karabiner-elements
    - keybase
    - moom
    - ngrok
    - quicklook-json
    - scre
    - sketch
    - slack
    - spotify
    - transmission
    - visual-studio-code
    - font-fira-code

  packages:
    - ack
    - bat
    - bazel
    - carthage
    - coreutils
    - direnv
    - displayplacer
    - dive
    - docker
    - envchain
    - fzf
    - github/gh/gh
    - git-delta
    - go
    - gradle
    - grc
    - grpcurl
    - helm
    - imagemagick
    - jq
    - kubernetes-cli
    - mitmproxy
    - node
    - pgweb
    - pnpm
    - rbenv
    - readline
    - ripgrep
    - screen
    - shellcheck
    - tfenv
    - tilt
    - tmux
    - tree
    - watchman
    - wget

link:
  shell/profile:             .profile
  bash/profile:              .bash_profile
  zsh/zshrc:                 .zshrc
  zsh/zshrc.d:               zshrc.d
  git/gitconfig:             .gitconfig
  git/gitignore:             .gitignore
  git/hooks:                 gitconfig/hooks
  grc:                       .grc
  karabiner:                 .config/karabiner
  mac/aliases:               .aliases
  mac/exports:               .exports
  mac/hushlogin:             .hushlogin
  mac/inputrc:               .inputrc
  ruby/irbrc:                .irbrc
  ruby/pryrc:                .pryrc
  screen/screenrc:           .screenrc
  tmux/tmux.conf:            .tmux.conf
  vim/gvimrc:                .gvimrc
  vim/vimrc:                 .vimrc
  vim:                       .config/nvim
  wget:                      .wgetrc

anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'
  libexec_dir: '{{ home_path }}/.anyenv/libexec'

golang:
  packages:

nodejs:
  default_packages_path: '{{ dotfiles_path }}/config/nodenv/default-packages'
  versions:
    - '19.6.0'
  plugins:
    - nodenv/nodenv-default-packages
