homebrew:
  applications:
    - 1password
    - alfred
    - anki
    - background-music
    - contexts
    - discord
    - docker
    - firefox
    - gitify
    - gitup
    - google-chrome
    - google-cloud-sdk
    - insomnia
    - iterm2
    - karabiner-elements
    - keybase
    - moom
    - ngrok
    - postgres
    - quicklook-json
    - sketch
    - slack
    - spotify
    - transmission
    - visual-studio-code

  packages:
    - ack
    - coreutils
    - direnv
    - docker
    - envchain
    - fzf
    - go
    - grc
    - imagemagick
    - jq
    - mitmproxy
    - node
    - pgweb
    - rbenv
    - readline
    - ripgrep
    - screen
    - shellcheck
    - terraform
    - tmux
    - tree
    - watchman
    - wget
    - yarn

npm:
  global:
    - neovim

link:
  bash/bash_profile:         .bash_profile
  bash/bashrc:               .bashrc
  bash/bashrc.d:             bashrc.d
  git/gitconfig:             .gitconfig
  git/gitignore:             .gitignore
  git/hooks:                 gitconfig/hooks
  grc:                       .grc
  karabiner:                 .config/karabiner
  mac/aliases:               .aliases
  mac/exports:               .exports
  mac/hushlogin:             .hushlogin
  mac/inputrc:               .inputrc
  ruby/irbrc:                .irbrc
  ruby/pryrc:                .pryrc
  screen/screenrc:           .screenrc
  tmux/tmux.conf:            .tmux.conf
  vim/gvimrc:                .gvimrc
  vim/vimrc:                 .vimrc
  vim:                       .vim
  wget:                      .wgetrc

golang:
  packages:
    # dev tools
    - golang.org/x/lint/golint           # Golint is a linter for Go source code
    - github.com/nsf/gocode              # An autocompletion daemon for the Go programming language
    - github.com/rogpeppe/godef          # find symbol information in Go source
    - github.com/izumin5210/gex/cmd/gex  # Dev tool dependency manager
