homebrew:
  taps:
    - jakehilborn/jakehilborn
  applications:
    # - 1password
    - alfred
    # - anki
    - antonve/tools/screen-manager
    - background-music
    - contexts
    # - discord
    - docker
    # - enjoyable
    - firefox
    - gitify
    # - google-chrome
    - google-cloud-sdk
    - imageoptim
    - insomnia
    - iterm2
    - karabiner-elements
    # - moom
    - postgres-unofficial
    - pure-prompt
    - quicklook-json
    # - slack
    - spotify
    - visual-studio-code
    - font-fira-code

  packages:
    - ack
    - bat
    - bazel
    - carthage
    - coreutils
    - direnv
    - displayplacer
    - dive
    - docker
    - envchain
    - fzf
    - github/gh/gh
    - git-delta
    - go
    - grc
    - grpcurl
    - helm
    - imagemagick
    - jq
    - kubernetes-cli
    - mitmproxy
    - pgweb
    - rbenv
    - readline
    - ripgrep
    - screen
    - shellcheck
    - tfenv
    - tilt
    - tmux
    - tree
    - watchman
    - wget

link:
  shell/profile:             .profile
  bash/profile:              .bash_profile
  zsh/zshrc:                 .zshrc
  zsh/zshrc.d:               zshrc.d
  git/gitconfig:             .gitconfig
  git/gitignore:             .gitignore
  git/hooks:                 gitconfig/hooks
  grc:                       .grc
  karabiner:                 .config/karabiner
  mac/aliases:               .aliases
  mac/exports:               .exports
  mac/hushlogin:             .hushlogin
  mac/inputrc:               .inputrc
  ruby/irbrc:                .irbrc
  ruby/pryrc:                .pryrc
  screen/screenrc:           .screenrc
  tmux/tmux.conf:            .tmux.conf
  vim/gvimrc:                .gvimrc
  vim/vimrc:                 .vimrc
  vim:                       .config/nvim
  wget:                      .wgetrc

nodejs:
  nvm_dir: '{{ home_path }}/.nvm'
  install_version: '--lts'
  default_alias: 'lts/*'
