- name:       antonve's dotfiles
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    is_ci:         '{{ lookup("env", "CI") | bool }}'

  roles:
    #  basic
    #-----------------------------------------------
    - role: link
      tags: ['basic', 'link']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'vim']