- name:       antonve's dotfiles
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    is_ci:         '{{ lookup("env", "CI") | bool }}'
    brew_bin_path: '/usr/local/bin'

  roles:
    #  basic
    #-----------------------------------------------
    - role: link
      tags: ['basic', 'link']

    #  install
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'homebrew']
    - role: npm
      tags: ['install', 'npm']

    #  programming languages
    #-----------------------------------------------
    - role: anyenv
      tags: ['lang', 'lang.anyenv']
    - role: nodejs
      tags: ['lang', 'lang.anyenv', 'lang.anyenv.nodejs']
    - role: golang
      tags: ['lang', 'golang']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'vim']

    #  system
    #-----------------------------------------------
    - role: zsh
      tags: ['system', 'system.zsh']
