- name:       antonve's dotfiles
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    is_ci:         '{{ lookup("env", "CI") | bool }}'

  roles:
    #  basic
    #-----------------------------------------------
    - role: link
      tags: ['basic', 'link']

    #  install
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'homebrew']

    - role: npm
      tags: ['install', 'npm']

    #  programming languages
    #-----------------------------------------------
    - role: golang
      tags: ['languages', 'golang']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'vim']
