if [ -f ~/.profile ]; then
  source ~/.profile
fi

config_paths=(
  ~/zshrc.d/languages/{golang,python,ruby}.zsh
  ~/zshrc.d/base/{aliases,autocomplete,functions,shell}.zsh
  ~/zshrc.d/envs/direnv.zsh
  ~/zshrc.d/tools/{fzf,google-cloud-sdk}.zsh
)

for configs in "${config_paths[@]}"; do
  for file in $configs; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
done;
unset file configs config_paths;
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/dotfiles/zsh/zshrc.work ] && source ~/dotfiles/zsh/zshrc.work
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

# pnpm
export PNPM_HOME="/Users/io/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "/Users/io/.bun/_bun" ] && source "/Users/io/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
