# Base configs
for file in ~/bashrc.d/base/{aliases,autocomplete,exports}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

# Programming language configs
for file in ~/bashrc.d/language/{golang}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Load direnv
eval "$(direnv hook bash)"

# Load fzf config
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
