config_paths=(
  ~/bashrc.d/languages/{golang,python,ruby}.bash
  ~/bashrc.d/base/{aliases,autocomplete,exports,shell}.bash
  ~/bashrc.d/envs/direnv.bash
  ~/bashrc.d/tools/{fzf,google-cloud-sdk}.bash
)

for configs in "${config_paths[@]}"; do
  for file in $configs; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
done;
unset file configs config_paths;
