config_paths=(
  ~/bashrc.d/base/{aliases,autocomplete,exports}.bash
  ~/bashrc.d/envs/direnv.bash
  ~/bashrc.d/languages/golang.bash
  ~/bashrc.d/tools/fzf.bash
)

for configs in "${config_paths[@]}"; do
  for file in $configs; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
  done;
done;
unset file configs config_paths;
